language: python

python:
  - "3.5"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite.travis_settings"
    - PYTHONPATH="/home/travis/build/pmontgo33/lawn_care_planner"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true

#commands to install dependencies
install:
  - sudo apt-get -y install build-essential libpq-dev python-dev
  - pip install -q -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres
  - python manage.py migrate

#command to run the test suite
script:
  - python manage.py test
