# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('zip_code', models.CharField(max_length=5)),
                ('grass_type', models.CharField(choices=[('KBG', 'Kentucky Bluegrass'), ('PRG', 'Perennial Ryegrass'), ('TTTF', 'Turf Type Tall Fescue')], max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
