# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_lawn_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacoverage', models.IntegerField(default=0)),
                ('elevation', models.FloatField(default=0.0)),
                ('elevationUnit', models.CharField(max_length=200)),
                ('stationid', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('maxdate', models.DateField()),
                ('mindate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('temp_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
