# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_weatherstation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherstation',
            old_name='name',
            new_name='name_name',
        ),
    ]
