# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20161123_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Grass Seed', 'Grass Seed'), ('Fertilizer', 'Fertilizer'), ('Weed Control', 'Weed Control'), ('Insect Control', 'Insect Control')], max_length=140)),
                ('links', jsonfield.fields.JSONField()),
                ('specs', jsonfield.fields.JSONField()),
            ],
        ),
    ]
