# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_lawnproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('Cool Season', 'Cool Season'), ('Warm Season', 'Warm Season')], max_length=200)),
                ('seed', models.BooleanField(default=True)),
                ('plugs', models.BooleanField(default=False)),
                ('mowing', jsonfield.fields.JSONField()),
                ('specs', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lawnproduct',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterField(
            model_name='lawn',
            name='grass_type',
            field=models.CharField(choices=[('KBG', 'Kentucky Bluegrass'), ('PRG', 'Perennial Ryegrass'), ('TTTF', 'Turf Type Tall Fescue'), ('BMG-C', 'Bermudagrass, common'), ('BMG-H', 'Bermudagrass, hybrid')], max_length=140),
        ),
    ]
