# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20170122_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='grass_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.GrassType'),
        ),
    ]
