# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_lawn_grass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawn',
            name='grass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GrassType'),
        ),
    ]
