# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20170425_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='weekly_notify',
            field=models.BooleanField(default=True),
        ),
    ]
