# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-16 19:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_lawn_weekly_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='temp_data',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
