# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_lawn_weekly_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawn',
            name='lime',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawn',
            name='organic',
            field=models.CharField(default='NP', max_length=2),
        ),
        migrations.AddField(
            model_name='lawn',
            name='phosphorus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawn',
            name='potassium',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawn',
            name='spring_seeding',
            field=models.BooleanField(default=False),
        ),
    ]
