# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20170531_2057'),
        ('planner', '0015_auto_20171216_1417'),
    ]

    operations = [
    ]
